# Generated by Django 2.2.28 on 2023-05-10 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20230509_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('availability', models.BooleanField(blank=True, default=True)),
                ('availability_change_date', models.DateField(verbose_name='availability change date')),
                ('content_change_date', models.DateField(verbose_name='content change date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('up', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('availability', models.BooleanField(blank=True, default=True)),
                ('availability_change_date', models.DateField(verbose_name='availability change date')),
                ('content_change_date', models.DateField(verbose_name='content change date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('begin', models.IntegerField()),
                ('end', models.IntegerField()),
                ('content', models.CharField(max_length=10000)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.File')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SectionKind')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Status')),
                ('statusData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StatusData')),
                ('up', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CodeSection')),
            ],
        ),
    ]
