# Generated by Django 2.2.28 on 2023-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_codesection_file_folder_sectionkind_status_statusdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesection',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='file',
            name='availability_change_date',
            field=models.DateTimeField(verbose_name='availability change date'),
        ),
        migrations.AlterField(
            model_name='file',
            name='content_change_date',
            field=models.DateTimeField(verbose_name='content change date'),
        ),
        migrations.AlterField(
            model_name='file',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='availability_change_date',
            field=models.DateTimeField(verbose_name='availability change date'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='content_change_date',
            field=models.DateTimeField(verbose_name='content change date'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
