# Generated by Django 2.2.28 on 2023-05-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mob',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
