# Generated by Django 2.2.28 on 2023-05-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_users_mob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AlterField(
            model_name='users',
            name='mob',
            field=models.IntegerField(null=True),
        ),
    ]
