# Generated by Django 2.2.28 on 2023-05-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230516_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
